--  This package was generated by Todo
package ADL_Config is
Vendor                         : constant String  := "STMicro";           -- From board definition
   Max_Mount_Points               : constant         := 2;                   -- From default value
   Max_Mount_Name_Length          : constant         := 128;                 -- From default value
   Runtime_Profile                : constant String  := "ravenscar-sfp";     -- From command line
   Device_Name                    : constant String  := "NUCLEO-H743ZI";     -- From board definition
   Device_Family                  : constant String  := "STM32H7";           -- From board definition
   Runtime_Name                   : constant String  := "ravenscar-sfp-stm32h743nucleo"; -- From default value
   Has_Ravenscar_Full_Runtime     : constant String  := "True";              -- From board definition
   CPU_Core                       : constant String  := "ARM Cortex-M7F";    -- From mcu definition
   Board                          : constant String  := "STM32H743_Nucleo"; -- From command line
   Has_ZFP_Runtime                : constant String  := "False";             -- From board definition
   Has_Ravenscar_SFP_Runtime      : constant String  := "True";              -- From board definition
   High_Speed_External_Clock      : constant         := 25000000;            -- From board definition
   Max_Path_Length                : constant         := 1024;                -- From default value
   Runtime_Name_Suffix            : constant String  := "stm32h743nucleo";    -- From board definition
   Architecture                   : constant String  := "ARM";               -- From board definition
end ADL_Config;
